[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get --assume-yes install libssl-dev:arm64",
    "apt-get --assume-yes install libfontconfig1-dev:arm64",
    "apt-get --assume-yes install libfreetype6-dev:arm64",
    "apt-get --assume-yes install libc6-dev:arm64"
]
